# Generated by Django 3.1.6 on 2021-02-15 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
        ('continent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('official_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fr_name', models.CharField(blank=True, max_length=255, null=True)),
                ('en_name', models.CharField(blank=True, max_length=255, null=True)),
                ('iso', models.CharField(blank=True, max_length=255, null=True)),
                ('iso3', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, max_length=255, null=True)),
                ('drapeau', models.FileField(blank=True, null=True, upload_to='images/country')),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('capital', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_capital', to='city.city')),
                ('continent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_capital', to='continent.continent')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
    ]
