# Generated by Django 3.1.6 on 2021-02-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='telephone_prefix',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Prefix'),
        ),
    ]
