# Generated by Django 3.1.6 on 2021-02-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20210216_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='drapeau',
            field=models.FileField(blank=True, null=True, upload_to='images/flags'),
        ),
    ]
