# Generated by Django 3.1.6 on 2021-02-16 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('continent', '0002_continent_code'),
        ('country', '0004_auto_20210216_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='continent_countries', to='continent.continent'),
        ),
    ]
