# Generated by Django 3.1.6 on 2021-02-17 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_auto_20210216_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
    ]
