# Generated by Django 3.1.6 on 2021-02-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
