# Generated by Django 3.1.6 on 2021-02-17 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continent', '0002_continent_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent',
            options={'ordering': ['name'], 'verbose_name': 'Continent', 'verbose_name_plural': 'Continents'},
        ),
    ]
